feature_names:
- open
- high
- low
- close
- volume
- sma_5
- sma_20
- sma_50
- ema_12
- ema_26
- rsi_14
- macd
- macd_signal
- bb_upper
- bb_lower
- atr_14
- price_change
- high_low_ratio
- volume_ratio
- volatility
- price_position
lookback_window: 100
n_features: 21
obs_dim: 2105
portfolio_features_dim: 5
