feature_names:
- open
- high
- low
- close
- volume
- sma_5
- sma_20
- sma_50
- ema_12
- ema_26
- rsi_14
- macd
- macd_signal
- bb_upper
- bb_lower
- atr_14
- hour_of_day
- day_of_week
- is_weekend
- price_change
- high_low_ratio
- volume_ratio
- volatility
- price_position
- hour_sin
- hour_cos
- dow_sin
- dow_cos
lookback_window: 100
n_features: 28
obs_dim: 2805
portfolio_features_dim: 5
